spring:
  application:
    name: icedlatteproject
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jwt:
    secret: ${JWT_SECRET}
    tokenDuration: ${JWT_EXPIRATION}